"""Turn the extracted first frames into (a) the poster each <video> shows
before it plays, sized for its slot, and (b) a 20px blur-up placeholder
inlined as a data URI so it paints before any request completes.
Writes src/posters.ts for the hero tiles and posters/lqip.json for the
static cards in index.html."""
import base64, io, json, pathlib
from PIL import Image

root = pathlib.Path(__file__).resolve().parents[2]
out = root / "public/assets/videos/posters"
posters: dict[str, dict[str, str]] = {}
for full in sorted(out.glob("*.full.jpg")):
    name = full.name[: -len(".full.jpg")]
    im = Image.open(full).convert("RGB")
    # Main-card slots top out at 468px CSS; small cards and tiles far less.
    cap = 960 if "main" in name else 320
    if im.width > cap:
        im = im.resize((cap, round(im.height * cap / im.width)), Image.LANCZOS)
    im.save(out / f"{name}.jpg", "JPEG", quality=82, optimize=True, progressive=True)
    tiny = im.resize((20, max(1, round(im.height * 20 / im.width))), Image.LANCZOS)
    buf = io.BytesIO(); tiny.save(buf, "JPEG", quality=35, optimize=True)
    posters[name] = {
        "poster": f"/assets/videos/posters/{name}.jpg",
        "lqip": "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode(),
    }
    full.unlink()
    print(f"{name:22s} poster {im.width}x{im.height} {(out / f'{name}.jpg').stat().st_size // 1024}KB  lqip {len(buf.getvalue())}B")
(out / "lqip.json").write_text(json.dumps(posters, indent=2) + "\n")
ts = "/* Generated by scripts/posters/build.sh - do not edit. */\n"
ts += "export const POSTERS: Record<string, { poster: string; lqip: string }> = " + json.dumps(posters, indent=2) + ";\n"
(root / "src/posters.ts").write_text(ts)
